### ISSUE TITLE
ODD 24.4 Objective 1: Integrate titiler-cmr

### ISSUE THREAD

**Issue by abarciauskas-bgse** [NASA-IMPACT/veda-ui#1054]
## Motivation /Description
Titiler-cmr creates map tiles dynamically using CMR query parameters, such as CMR collection concept id. Titiler-cmr has the potential to expose many of NASA’s operational datasets for visualization without need for an additional metadata store or creation and maintenance of pre-generated imagery pipelines.
This objective is to complete the integration of titiler-cmr into raster layers in the veda-ui library.

```[tasklist]
### Success Criteria
- [ ] 1 dataset in VEDA staging is tiled using titiler-cmr
```

Risks/Dependencies
- With the current refactoring of the UI, there is a bit of a risk / dependency to make sure the integration works amongst the other data sources.

```[tasklist]
### Tasks
- [ ] https://github.com/NASA-IMPACT/veda-ui/issues/1055
- [ ] https://github.com/NASA-IMPACT/veda-ui/issues/1056
```
