### ISSUE TITLE
Template instance styling and small bugs cleanup

### ISSUE THREAD

**Issue by aboydnw** [NASA-IMPACT/veda-ui#1282]
- [x] Map legend fonts @hanbyul-here 
- [x] Layout overflows in E&A @hanbyul-here 
- [x] Close new USWDS page header dropdown when clicking outside of it https://github.com/NASA-IMPACT/veda-ui/issues/1296
- [x] Add the About page + the Contact Us modal (probably a quick fix) related to #1313 
- [x] Rest of content in #1313 
- [x] General cleanup of margins and paddings
- [x] Links are same color as background, example in Hurricane Maria story with additional resources at bottom
- [x] Story headers are missing (unless this was intentional?) even though they are in place for the dataset overview page (@sandrahoang686 )

---

- [x] Make Date function work with Map component @hanbyul-here  - This might need more efforts than 'polishing' 
- [x] #1402
- [x] #1418
https://deploy-preview-41--veda-ui-next-test.netlify.app/stories/air-quality-and-covid-19
- [x] Datalayer info modal not redirecting to data-catalog page (@sandrahoang686 )
- [x] E&A is not fully visible until you scroll all the way to the bottom of the list of data layers and scroll down further to hide the page header

**Comment by aboydnw** [comment]
For the Contact Us form, we're probably okay just pointing to the same form as the Earthdata instance, so we don't have to monitor more locations for responses

https://docs.google.com/forms/d/17tvlyzbLNl-3KrUoHMczhOH1Me_1c1i5hViZULIsTZw/edit
