### ISSUE TITLE
Remove Thematic areas as a content type

### ISSUE THREAD

**Issue by danielfdsilva** [NASA-IMPACT/veda-ui#494]
With the upcoming dashboard v2, the thematic areas as a unit of dataset and discovery grouping no longer make sense and they should be removed from the app.

The thematic areas should become just a taxonomy by which datasets and discoveries can be filtered.

### Tasks
- [ ] Remove thematic areas related content, converting them to a taxonomy
- [ ] Figure out what to do with the long form content of thematic areas (EIS for example)
- [x] Rename/cleanup the "thematic resolver module"
- [x] Remove thematic references from the routes and ensure proper content redirection
- [ ] Update veda-config documentation

**Comment by danielfdsilva** [comment]
Remaining items tracked in #509 and #510
