### ISSUE TITLE
[E & A] Make dataset/layer metadata information available

### ISSUE THREAD

**Issue by faustoperez** [NASA-IMPACT/veda-ui#811]
#### Problem
Context and metadata information on datasets and layers is not available without leaving the Exploration and Analysis page. Users lack the context on:

- Description
- Geographic coverage
- Spatial resolution
- Temporal resolution
- Source
- Citation
- Etc.

#### Tasks
- [x] Identify UI elements where we can link / surface that information
- [x] Provide a standardized structure for the displayed metadata
- [x] Identify UI points where it makes sense to link to the Overview page
- [x] Create the visual designs

**Comment by faustoperez** [comment]
Here are the designs for the info modal. 

Link to Figma file 👉 https://www.figma.com/file/9INQauBWhiRxvOWDGhRrxO/US-GHG-Center?type=design&node-id=821%3A1763&mode=design&t=7ar7IlCwHjYGLLbQ-1

The changes are:

### Dataset panel

- Change layer option icons: we have simplified the layer action icons, displaying the `info` only, and the rest of the actions under a `more` icon. Related #774 

<img width="1728" alt="US GHG Center - Timeline + data panel - options" src="https://github.com/NASA-IMPACT/veda-ui/assets/12268629/ba021bd3-379b-440a-9dbc-296b02352931">


### Info modal

- Not structured text (for now). Description from the dataset overview, then the following fields in a bulleted list (for GHG Center):
    - Source
    - Topic
    - Product type
    - Gas
    - Temporal Extent
    - Temporal Resolution
    - Spatial Extent
    - Spatial Resolution
    - Data Units
    - Data Type
    - Data Latency

<img width="900" alt="Info modal - single dataset - text" src="https://github.com/NASA-IMPACT/veda-ui/assets/12268629/73796be3-1952-4ca6-a5d7-ef4aa698aa34">
