### ISSUE TITLE
[E & A] Fast follow ups after internal review

### ISSUE THREAD

**Issue by faustoperez** [NASA-IMPACT/veda-ui#856]
This is a placeholder ticket if there are any fast design follow-ups after enabling the new E&A release
```[tasklist]
### Tasks
- [x] select modal - update filter to remove redundant "Name" option
- [x] card - remove link from collection title
- [x] info modal - change button text to "Open in Data Catalog"
- [x] select modal - remove link from collection title on top of the modal
- [x] analysis - add stat analysis menu back to chart ( @faustoperez to follow up with design) https://github.com/NASA-IMPACT/veda-ui/pull/860
- [x] info modal - remove link from collection title
- [x] select modal - update `show/hide` filters to be optional depending on view https://developmentseed.slack.com/archives/C03LGTM2SSH/p1709062753753879?thread_ts=1709050497.517369&cid=C03LGTM2SSH
- [x] Update linking to Data Catalog to open a new tab (ticket [here](https://github.com/NASA-IMPACT/veda-ui/issues/861))
```

**Comment by faustoperez** [comment]
@sandrahoang686 @j08lue Here's a quick mockup of what the analysis options could look like. The `cogs` icon should stick to the top right corner and always be visible (during analysis mode).

<img width="1728" alt="US GHG Center - Timeline + analysis options" src="https://github.com/NASA-IMPACT/veda-ui/assets/12268629/f75c861e-f631-4836-adaa-04918c7db8c3">

As a side note, in the near future we should revisit the analysis chart to work on the following:

- Timeline analysis states
- add 0 reference to vertical legend
- show multiple charts
- expand/collapse etc.
- chart tooltip
- chart styles
- etc.

**Comment by sandrahoang686** [comment]
PR #859 
Accomplishes the first 4 tasks...
- select modal - update filter to remove redundant "Name" option
- card - remove link from collection title
- info modal - change button text to "Open in Data Catalog"
- select modal - remove link from collection title on top of the modal

Analysis change will take a bit longer so separate PR to follow

**Comment by sandrahoang686** [comment]
This is also to be done: https://github.com/NASA-IMPACT/veda-ui/issues/861

**Comment by sandrahoang686** [comment]
For task => select modal - update show/hide filters to be optional depending on view

https://github.com/NASA-IMPACT/veda-ui/pull/862#pullrequestreview-1906792573 merged
