### ISSUE TITLE
Develop and Continue to prove out NextJs instance Prototype as a consumer of the veda-ui library

### ISSUE THREAD

**Issue by aboydnw** [NASA-IMPACT/veda-ui#997]
### Context

Followup ticket once identified blockers are removed
Order of tickets: #978  /  #975   =>   #800    =>     this ticket
Follow up ticket from #947

### Description
This ticket is too big and will need to be broken out into separate issues. _This is mostly a tracker ticket._
This ticket is the continuation and development to prove out the nextJs Prototype instance for the veda2 Refactor.

#### Goal
* Prove out the ability to render mdx content without the parcel resolver interference
* Build out and showcase the Data Catalog Page with importable layout
* Display a story with a MapBlock (dependent on faux modules) component successfully

**Linked Issues to complete:**
- [x] Decision on the strategy to replace Global data exposure provided by Parcel Resolver https://github.com/NASA-IMPACT/veda-ui/issues/978
   - [ ] Implement Data Exposure Store in nextJs Prototype and for veda-ui MapBlock component https://github.com/NASA-IMPACT/veda-ui/issues/1002
      - [ ] Implement Data Catalog Page with Page Layout components from veda-ui [_issue to be created & linked_]
- [x] Move VEDA data types, utility functions to source code https://github.com/NASA-IMPACT/veda-ui/issues/975
- [x] Implementation - Create layer / build pipeline to access core ui library https://github.com/NASA-IMPACT/veda-ui/issues/800

**Comment by aboydnw** [comment]
@sandrahoang686 now that we have the prototype instance wrapped up, should we close this ticket?
